### ISSUE TITLE
Org 단위가 아닌 Repo 레벨의 멤버 관리 피쳐

### ISSUE THREAD

**Issue by kkweon** [codingpot/github-org-member-manage-action#8]
예를 들어 특정리포에만 collaborator추가하기

**Comment by mrchypark** [comment]
이렇게 하는건 어떤가요?

```
# members.yaml
org_name: codingpot

admins:
  - kkweon
  - kkweon2

members:
  - deepdiver1
  - deepdiver2

---
org_name: codingpot/github-repo-name
members:
  - mrchypark
```

**Comment by kkweon** [comment]
공식언어를 사용하면 

```yaml
repo_name: github-repo-name
collaborators:
- mrchypark
```

이렇게 되면 좋겠습니다.
